name: Run tutorials with all components from containers
on:
  push:
    branches:
      - add-nightly-tests
jobs:
  run-flow-over-heated-plate:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/precice/openfoam-adapter:latest
      options: --user root
    steps:
      - name: Print environment
        run: |
          env && whoami
      - name: List files
        run: |
          ls -la /home
      - name: Write a dummy file
        run: |
          cd /home/precice && date | tee dummy.log
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: test
        run: |
          ls
        