name: Run tutorials with all components from containers
on:
  push:
    branches:
      - add-nightly-tests
jobs:
  run-flow-over-heated-plate:
    runs-on: ubuntu-latest
    container: ghcr.io/precice/openfoam-adapter:latest
    steps:
      - name: Print environment
        run: |
          env
      - name: Manually clone repo
        run: |
          git clone https://github.com/precice/tutorials.git
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: test
        run: |
          ls
        