name: Run tutorials with all components from containers
on:
  push:
    branches:
      - add-nightly-tests
jobs:
  run-flow-over-heated-plate:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/precice/openfoam-adapter:latest
      options: --user root
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Switch user to precice
        run: |
          su - precice
      - name: Run an OpenFOAM-OpenFOAM case
        run: |
          cd /home/precice/tutorials/flow-over-heated-plate/
          (cd fluid-openfoam && ./run.sh &)
          (cd solid-openfoam && ./run.sh &)  
        