name: Run tutorials with all components from containers
on:
  push:
    branches:
      - add-nightly-tests
jobs:
  run-flow-over-heated-plate:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/precice/openfoam-adapter:latest
      options: --user precice
    steps:
      - name: Get ownership of workspace
        run: sudo chown -R $USER:$USER /__w/tutorials/
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run an elastic-tube-1d case
        run: |
          cd elastic-tube-1d
          (cd fluid-cpp && mkdir build && cd build && cmake .. && make all && cd .. && ./run.sh | tee fluid-cpp.log 2>&1 &)
          (cd solid-cpp && mkdir build && cd build && cmake .. && make all && cd .. && ./run.sh | tee solid-cpp.log 2>&1 &)
      - name: Run an OpenFOAM-OpenFOAM case
        run: |
          export USER=precice
          export HOME=/home/precice
          openfoam2012 env
          cd flow-over-heated-plate/
          (cd fluid-openfoam && /usr/bin/openfoam2012 ./run.sh | tee fluid-openfoam.log 2>&1 &)
          (cd solid-openfoam && /usr/bin/openfoam2012 ./run.sh | tee solid-openfoam.log 2>&1 &)
      - name: Archive logs
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: |
            elastic-tube-1d/fluid-cpp/fluid-cpp.log
            elastic-tube-1d/solid-cpp/solid-cpp.log
            flow-over-heated-plate/fluid-openfoam/fluid-openfoam.log
            flow-over-heated-plate/solid-openfoam/solid-openfoam.log
      - name: Archive case files
        uses: actions/upload-artifact@v2
        with:
          name: case-files
          path: |
            flow-over-heated-plate/fluid-openfoam/*
            flow-over-heated-plate/solid-openfoam/*
        